import swaggerAutogen from 'swagger-autogen';

const outputFile = './swagger_output.json';
const endpointsFile = ['./src/routes/userRoutes.js', './src/routes/ownerRoutes.js'];


const doc = {
	info: {
		version: '1.0.0',
		title: 'Coworking Doc',
		description:
			'Documentation automatically generated by the <b>swagger-autogen</b> module.'
	},
	host: 'localhost:3000',
	basePath: '/',
	consumes: ['application/json'],
	produces: ['application/json'],
	tags: [
		{
			name: 'User',
			description: "User's endpoint"
		},
		{
			name: 'Owner',
			description: "Owner's endpoint"
		}
	]
};

swaggerAutogen(outputFile, endpointsFile, doc);
