import swaggerAutogen from 'swagger-autogen';

const outputFile = './swagger_output.json';
const endpointsFile = ['./src/routes/userRoutes.js', './src/routes/ownerRoutes.js'];


const doc = {
	info: {
		version: '1.0.0',
		title: 'Coworking Doc',
		description:
			'Documentation automatically generated by the <b>swagger-autogen</b> module.'
	},
	host: 'localhost:3000',
	basePath: '/',
	consumes: ['application/json'],
	produces: ['application/json'],
	tags: [
		{
			name: 'User',
			description: "User's endpoint"
		},
		{
			name: 'Owner',
			description: "Owner's endpoint"
		}
	],
	definitions: {
		User: {
			id: '0293498asdfh384734ghfhk',
			firstName: 'José',
			lastName: 'Silva',
			cpf: '000.000.000-00',
			email: 'silvajose@gmail.com',
			birthDate: '02/12/1978',
			phoneNumber: '(99)99999-9999',
			password: '1237csdf439',
			profilePhoto:
				'/users/profilePhotos/id:3128758325.jpg',
			balanceAccount: 0.00
			// Adicionar cidade na documentacao
		},
		CreateUser: {
			$firstName: 'José',
			$lastName: 'Silva',
			$cpf: '000.000.000-00',
			$email: 'silvajose@gmail.com',
			$birthDate: '02/12/1978',
			$phoneNumber: '(99)99999-9999',
			$password: '234rhkwdhfk89',
			profilePhoto:
				'/users/profilePhotos/id:3128758325.jpg'
			// Adicionar cidade na documentacao
		},
		CreateOwner: {
			$nomeEmpresarial: "Marcio Souza EIRELI",
			$nomeFantasia: "Marcio Embalagens",
			$firstName: '',
			$lastName: '',
			$document: '000.000.000-00',
			$email: 'silvajose@gmail.com',
			$phoneNumber: '(99)99999-9999',
			$password: '234rhkwdhfk89',
			profilePhoto:
				'/users/profilePhotos/id:3128758325.jpg'
			// Adicionar cidade na documentacao
		}
	}
};

swaggerAutogen(outputFile, endpointsFile, doc);
