import { readFileSync } from 'node:fs';
import express from 'express';
import swaggerUi from 'swagger-ui-express';
import users from './userRoutes.js';
import owners from './ownerRoutes.js';
import spaces from './spaceRoutes.js';
import blockCategory from './blockCategoryRoutes.js';
import block from './blockRoutes.js';
import blockReservation from './blockReservationRoutes.js';

// Generated by `npm run swagger`. Read at runtime instead of `import ... assert { type: 'json' }`,
// whose `assert` keyword was removed in Node 22 (it is `with` there).
const swaggerFile = JSON.parse(readFileSync(new URL('../../swagger/swagger_output.json', import.meta.url), 'utf8'));

const routes = (app) => {
	app.use('/doc', swaggerUi.serve, swaggerUi.setup(swaggerFile));
	app.use(express.json(), users);
	app.use(express.json(), owners);
	app.use(express.json(), spaces);
	app.use(express.json(), blockCategory);
	app.use(express.json(), block);
	app.use(express.json(), blockReservation);
};

export default routes;
