import swaggerAutogen from 'swagger-autogen';

const outputFile = './swagger_output.json';
const endpointsFile = [
	'./src/routes/userRoutes.js',
	'./src/routes/ownerRoutes.js',
	'./src/routes/spaceRoutes.js',
	'./src/routes/blockRoutes.js',
	'./src/routes/blockCategoryRoutes.js',
	'./src/routes/blockReservationRoutes.js'
];

const doc = {
	info: {
		version: '1.0.0',
		title: 'Coworking Doc',
		description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.'
	},
	host: 'localhost:3000',
	basePath: '/',
	consumes: ['application/json'],
	produces: ['application/json'],
	securityDefinitions: {
		apiKeyAuth: {
			type: 'apiKey',
			in: 'header',
			name: 'Authorization',
			description: 'JWT returned by /userLogin or /ownerLogin. Either the raw token or "Bearer <token>".'
		}
	},
	security: [{ apiKeyAuth: [] }]
};

swaggerAutogen(outputFile, endpointsFile, doc);
